#For use in gui.py

DEFAULT_DELETE_WINDOW_PROTOCOL = "WM_DELETE_WINDOW"
DEFAULT_RESOLUTION = "512x512"
DEFAULT_FONT = "Arial"
DEFAULT_TEXTBOX_HEIGHT = 1
DEFAULT_TEXTBOX_WIDTH = 50
DEFAULT_TEXTBOX_STATE = "disabled"
DEFAULT_ENTRY_SIZE = 50