#For use in gui.py

LABEL_TEXT_WELCOME = "Welcome, please choose an option below:"
LABEL_TEXT_ENTER_DATA_API_KEY = "Please enter your Youtube Data API Key below:"
LABEL_TEXT_API_SELECTION = "Please select an API category below:"
LABEL_TEXT_NON_API_SELECTION = "Please select an option below:"
LABEL_TEXT_VIDEOS_SELECTION = "Please select an action below:"
LABEL_TEXT_ENTER_VIDEO_URL = "Enter a Youtube Video URL"
LABEL_TEXT_SELECT_THUMBNAIL_SIZE = "Select a thumbnail size"
LABEL_TEXT_SELECT_EXTRACT_ID = "Select which type of ID to extract"
LABEL_TEXT_ENTER_PLAYLIST_URL = "Enter a Youtube Playlist URL"
LABEL_TEXT_ENTER_CHANNEL_URL = "Enter a Youtube Channel URL"
LABEL_TEXT_SELECT_OPTION_BELOW = "Please select an action below:"

BUTTON_TEXT_API_RELATED = "API Related"
BUTTON_TEXT_NON_API_RELATED = "Non-API Related"
BUTTON_TEXT_CLOSE = "Close"
BUTTON_TEXT_VIDEOS = "Videos"
BUTTON_TEXT_CHANNELS = "Channels"
BUTTON_TEXT_PLAYLISTS = "Playlists"
BUTTON_TEXT_EXTRACT_IDS = "Extract IDs From URLs"
BUTTON_TEXT_BACK = "Back"
BUTTON_TEXT_GET_THUMBNAIL_URL = "Get Thumbnail URL"
BUTTON_TEXT_GO = "Go"
BUTTON_TEXT_GET_NUM_VIEWS = "Get Number of Views"
BUTTON_TEXT_GET_STATS = "Get Channel Statistics"

DROPDOWN_TEXT_DEFAULT = "Default"
DROPDOWN_TEXT_MEDIUM = "Medium"
DROPDOWN_TEXT_HIGH = "High"
DROPDOWN_TEXT_STANDARD = "Standard"

MESSAGEBOX_TITLE_CONFIRM_CLOSE = "Close Youtube API GUI?"
MESSAGEBOX_MESSAGE_CONFIRM_CLOSE = "Are you sure you want to close Youtube API GUI?"

WINDOW_TITLE_ROOT = "Youtube API GUI"
WINDOW_TITLE_API_SELECTION = "Youtube API GUI: API Selection"
WINDOW_TITLE_ENTER_DATA_API_KEY = "Youtube API GUI: Enter API Key"
WINDOW_TITLE_NON_API_SELECTION = "Youtube API GUI: Non-API Selection"
WINDOW_TITLE_VIDEOS_SELECTION = "Youtube API GUI: Videos"
WINDOW_TITLE_GET_THUMBNAIL_URL = "Youtube API GUI: Video Thumbnail URL"
WINDOW_TITLE_EXTRACT_IDS_SELECTION = "Youtube API GUI: Extract ID Selection"
WINDOW_TITLE_EXTRACT_PLAYLIST_ID = "Youtube API GUI: Extract Plyalist ID From URL"
WINDOW_TITLE_EXTRACT_CHANNEL_ID = "Youtube API GUI: Extract Channel ID From URL"
WINDOW_TITLE_EXTRACT_VIDEO_ID = "Youtube API GUI: Extract Video ID From URL"
WINDOW_TITLE_VIDEO_GET_NUM_VIEWS = "Youtube API GUI: Get the Number of Views of a Video From URL"
WINDOW_TITLE_CHANNELS_SELECTION = "Youtube API GUI: Channels"